# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: audiobook
      POSTGRES_USER: book
    ports:
      - 5432:5432


#version: '3.3'
#services:
#  db:
#    image: postgres:12
#    environment:
#      POSTGRES_DB: audiobook
#      POSTGRES_PASSWORD: password
#      POSTGRES_USER: book
#    volumes:
#      - postgresData:/var/lib/postgresql/data
#    networks:
#      - network
#  lydbook:
#    image: shatterhand/lydbook:latest
#    environment:
#      DATABASE_PASSWORD: password
#      POSTGRES_HOST: db
#    ports:
#      - 8080:8080
#    volumes:
#      - bookData:/data
#    networks:
#      - network
#networks:
#  network:
#volumes:
#  postgresData:
#    driver: local
#  bookData:
#    driver: local
