    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Setup JDK
            uses: actions/setup-java@v1
            with:
              java-version: 11
          - run:  ./gradlew clean test
